language: node_js

node_js:
  = "6"
  - "7"
  - "8"
  - "9"
  - "10"

sudo: false

install:
  - yarn install
  - yarn global add codecov

script:
  - yarn run test:coverage
  - codecov

cache:
  yarn: true
  directories:
  - node_modules
